name: CI

on: [push]

jobs:
    frontend:
        runs-on: ubuntu-18.04
        steps:
          - name: Checkout this repo
            uses: actions/checkout@v1

          - name: Install nodejs
            uses: actions/setup-node@v1.3.0
            with:
                node-version: 13.6.0

          - name: Lint
            run:  cd frontend npm && ci && npm run-script lint

          - name: Build
            run: cd frontend && npm run-script build

          - name: Test
            run: cd frontend && npm run-script test

          - name: Send notification
            uses: yanzay/notify-telegram@v0.1.0
            if: always()
            with:
                chat: ${{ secrets.TELEGRAM_CHAT_ID }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                status: ${{ job.status }}
    backend:
        runs-on: ubuntu-18.04
        steps:
          - name: Checkout this repo
            uses: actions/checkout@v1

          - name: Build
            uses: actions-rs/cargo@v1
            with:
                command: build
                args: --manifest-path backend/Cargo.toml

          - name: Test
            uses: actions-rs/cargo@v1
            with:
                command: test
                args: --manifest-path backend/Cargo.toml

          - name: Dist backend
            run: (cd backend && cargo xtask dist)

          - name: Send notification # FIXME: find a way to extract this into a job (deduplicate notifications)
            uses: yanzay/notify-telegram@v0.1.0
            if: always()
            with:
                chat: ${{ secrets.TELEGRAM_CHAT_ID }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                status: ${{ job.status }}


    deploy:
        runs-on: ubuntu-18.04
        needs: [frontend, backend]
        if: github.ref == 'master'
        steps:
          - name: deploy to Heroku
            env:
                HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
                HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
            run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
