name: CI

on: [push]

jobs:
    frontend:
        runs-on: ubuntu-18.04
        steps:
          - name: Checkout this repo
            uses: actions/checkout@v1

          - name: Install nodejs
            uses: actions/setup-node@v1.3.0
            with:
                node-version: 13.6.0

          - name: Lint
            run: echo "FIXME(add linting)"

          - name: Build
            run: echo "FIXME(add building)"

          - name: Test
            run: echo "FIXME(add testing)"

          - name: Send notification
            uses: yanzay/notify-telegram@v0.1.0
            if: always()
            with:
                chat: ${{ secrets.TELEGRAM_CHAT_ID }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                status: ${{ job.status }}
    backend:
        runs-on: ubuntu-18.04
        steps:
          - name: Checkout this repo
            uses: actions/checkout@v1

          - name: Build
            uses: actions-rs/cargo@v1
            with:
                command: build
                args: --manifest-path backend/Cargo.toml

          - name: Test
            uses: actions-rs/cargo@v1
            with:
                command: test
                args: --manifest-path backend/Cargo.toml

          - name: Dist backend
            run: (cd backend && cargo xtask dist)

          - name: Send notification # FIXME: find a way to extract this into a job (deduplicate notifications)
            uses: yanzay/notify-telegram@v0.1.0
            if: always()
            with:
                chat: ${{ secrets.TELEGRAM_CHAT_ID }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                status: ${{ job.status }}


    deploy:
        runs-on: ubuntu-18.04
        needs: [frontend, backend]
        if: github.ref == 'master'
        steps:
          - name: Deploy
            run: echo "FIXME(add deployment)"
