[package]
name = "xtask"
version = "0.1.0"
authors = ["100-debug-hours <gersoh3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = "0.3.1"
anyhow = "1.0.26"
